--- 
framework: 
  AdminMode: 0
  ApplicationClass: TestApp::Mason
  ApplicationName: TestApp-Mason
  ApplicationUUID: 691A2590-F25E-11DD-9995-406635203BE5
  ConfigFileVersion: 5
  Database: 
    AutoUpgrade: 1
    CheckSchema: 1
    Database: testapp_mason
    Driver: SQLite
    Host: localhost
    Password: ''
    RecordBaseClass: Jifty::DBI::Record::Cachable
    User: ''
    Version: 0.0.1
  DevelMode: 0
  L10N: 
    PoDir: share/po
  LogLevel: INFO
  Mailer: Sendmail
  MailerArgs: []

  Plugins: []
  PubSub: 
    Backend: Memcached
    Enable: ~
  SkipAccessControl: 0
  TemplateClass: TestApp::Mason::View
  View: 
    Handlers: 
      - Jifty::View::Mason::Handler
  Web: 
    BaseURL: http://localhost
    DataDir: var/mason
    Globals: []

    MasonConfig: 
      autoflush: 0
      default_escape_flags: h
      error_format: text
      error_mode: fatal
    Port: 8888
    ServeStaticFiles: 1
    StaticRoot: share/web/static
    TemplateRoot: share/web/templates
