--- 
framework: 
  AdminMode: 0
  ApplicationClass: TestApp::Plugin::PasswordAuth
  ApplicationName: TestApp-Plugin-PasswordAuth
  ApplicationUUID: E6B4180A-C68F-11DB-893B-FEFB1AECF28B
  Database: 
    CheckSchema: 1
    Database: testapp_plugin_passwordauth
    Driver: SQLite
    Host: localhost
    Password: ''
    RecordBaseClass: Jifty::DBI::Record::Cachable
    User: ''
    Version: 0.0.1
  DevelMode: 0
  L10N: 
    PoDir: share/po
  LogLevel: DEBUG
  Mailer: IO
  MailerArgs:
    - %log/mail.log%
  Plugins: 
    - AdminUI: {}
    - Authentication::Password: {}
    - CompressedCSSandJS: {}
    - OnlineDocs: {}
    - REST: {}
  TemplateClass: TestApp::Plugin::PasswordAuth::View
  Web: 
    BaseURL: http://localhost
    DataDir: var/mason
    Globals: []
    MasonConfig: 
      autoflush: 0
      default_escape_flags: h
      error_format: text
      error_mode: fatal
    Port: 8888
    ServeStaticFiles: 1
    StaticRoot: share/web/static
    TemplateRoot: share/web/templates
