--- 
framework: 
  AdminMode: 1
  ApplicationClass: TestApp::JiftyJS
  ApplicationName: TestApp::JiftyJS
  ApplicationUUID: F43CA57E-A4BE-11DC-A07C-465A83BE23AB
  ConfigFileVersion: 3
  Database: 
    CheckSchema: 1
    Database: testapp_jiftyjs
    Driver: SQLite
    Host: localhost
    Password: ''
    RecordBaseClass: Jifty::DBI::Record::Cachable
    User: ''
    Version: 0.0.1
  DevelMode: 1
  L10N: 
    PoDir: share/po
    AllowedLang:
      - en
      - zh_tw
  LogLevel: INFO
  Mailer: Sendmail
  MailerArgs: []

  Plugins: 
    - I18N: { js: 1 }

    - 
      LetMe: {}

    - 
      SkeletonApp: {}

    - 
      REST: {}

    - 
      Halo: {}

    - 
      ErrorTemplates: {}

    - 
      OnlineDocs: {}

    - 
      CompressedCSSandJS: {}

    - 
      AdminUI: {}

  PubSub: 
    Backend: Memcached
    Enable: ~
  SkipAccessControl: 0
  TemplateClass: TestApp::JiftyJS::View
  Web: 
    BaseURL: http://localhost
    DataDir: var/mason
    Globals: []

    MasonConfig: 
      autoflush: 0
      default_escape_flags: h
      error_format: text
      error_mode: fatal
    Port: 8888
    ServeStaticFiles: 1
    StaticRoot: share/web/static
    TemplateRoot: share/web/templates
