--- 
framework: 
  AdminMode: 0
  ApplicationClass: TestApp::Regions
  ApplicationName: TestApp-Regions
  ApplicationUUID: B2619C96-9EC7-11DD-8442-E9B62EB97401
  ConfigFileVersion: 4
  Database: 
    AutoUpgrade: 1
    CheckSchema: 1
    Database: testapp_regions
    Driver: SQLite
    Host: localhost
    Password: ''
    RecordBaseClass: Jifty::DBI::Record::Cachable
    User: ''
    Version: 0.0.1
  DevelMode: 0
  L10N: 
    PoDir: share/po
  LogLevel: INFO
  Mailer: Sendmail
  MailerArgs: []

  Plugins: 
    - 
      LetMe: {}

    - 
      SkeletonApp: {}

    - 
      REST: {}

    - 
      Halo: {}

    - 
      ErrorTemplates: {}

    - 
      OnlineDocs: {}

    - 
      CompressedCSSandJS: {}

    - 
      AdminUI: {}

  PubSub: 
    Backend: Memcached
    Enable: ~
  SkipAccessControl: 0
  TemplateClass: TestApp::Regions::View
  View: 
    FallbackHandler: Jifty::View::Mason::Handler
    Handlers: 
      - Jifty::View::Static::Handler
      - Jifty::View::Declare::Handler
      - Jifty::View::Mason::Handler
  Web: 
    BaseURL: http://localhost
    DataDir: var/mason
    Globals: []

    MasonConfig: 
      autoflush: 0
      default_escape_flags: h
      error_format: text
      error_mode: fatal
    Port: 8888
    ServeStaticFiles: 1
    StaticRoot: share/web/static
    TemplateRoot: share/web/templates
